[network]
    # Shown as 'Organization' for which the certificates are issued.
    name = "My Network"
    # Your email address. Embedded in the certificate, no other uses.
    email = "my.email@gmail.com"
    # Optional location where the certificates are deployed.
    country = "US"
    province = "WA"

    # Whether creating a new, or using an existing certificate authority,
    # this specifies the prefix of a certificate and a key.
    # - Certificate needs a ".crt" suffix, and
    # - Key needs a ".key" suffix.
    root_ca_name = "personal_ca"
    # When generating a new root_ca, this specifies its validity duration.
    # Safe to leave empty and use defaults.
    root_ca_validity_days = 3650

[sites."srv.domainname.net"]
    # Optional name.
    name = "Server"
    # Optional certificate validity length. Note that sites with unusually
    # long expiration dates (>2 years) will likely be flagged by most browsers.
    crt_validity_days = 365
    alt_names = ["backup.domainname.net", "srv", "backup", "192.168.0.2"]

[sites."dns.domainname.net"]
    name = "PiHole"
    alt_names = ["dns", "192.168.0.3"]

